#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'shaderapivulkan'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'SHADER_DLL_EXPORT',
		'PROTECTED_THINGS_ENABLE'
	])

	if conf.env.DEST_OS == 'android':
		conf.check(lib='openxr_loader', uselib_store='OPENXR')

def build(bld):
	source = [
		'shaderapivulkan.cpp',
		'../../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
		'../'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','tier1']
	linkflags = []

	if bld.env.DEST_OS == 'android':
		source += ['../../launcher/android/vr_xr_vulkan.cpp']
		includes += ['../../openxr_sdk/include', '../../launcher/android']
		libs += ['OPENXR']
		linkflags += ['-lvulkan']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		linkflags = linkflags,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
